# Organization of the different stages and jobs:
# build:
#  |_ cppcheck (C++ static analysis & coverage)
#  |_ py-pytest (Python unit tests)
#  |_ sphinx-build (documentation)
#  |_ unit-cpp-test (C++ unit tests)
#
# test:
#  |_ py-black (Python code formatting)
#  |_ py-lint (static analysis with Pylint)
#  |_ py-mypy (static type checking with Mypy)
#  |_ py-trivy (dependency scanning)
#  |_ sonar (SonarQube analysis)

spec:
  # Define input parameters for the TBC pipeline.
  inputs:
    # Test stage definition.
    test-cpp:
      type: boolean
      default: true
---
include:
  - component: $CI_SERVER_FQDN/to-be-continuous/python/gitlab-ci-python@8.1.3  # TBC Python component version
    # Default stage for jobs is build.
    # Below is the list of items to contains.
    inputs:
      image: ${UL_ARTIFACTORY_HOST}/publicremotes-docker/python:3.9 
      pytest-enabled: true
      pylint-enabled: true
      black-enabled: true
      mypy-enabled: true
      build-system: setuptools
      # Install libsgm test dependencies (see setup.cfg file)
      extra-deps: test
  - component: $CI_SERVER_FQDN/to-be-continuous/sonar/gitlab-ci-sonar@5.0.1
    inputs:
      host-url: "${UL_SONARQUBE_URL}"
      quality-gate-enabled: true
  - component: $CI_SERVER_FQDN/to-be-continuous/sphinx/gitlab-ci-sphinx@1.5.0
    inputs:
      image: ${UL_ARTIFACTORY_HOST}/ghcr.io/sphinx-doc/sphinx-ci:latest
      project-dir: docs
      build-args: --fail-on-warning  # fail if a warning is raised

variables:
  # default production ref name (pattern)
  PROD_REF: /^(master|main)$/
  # default integration ref name (pattern)
  # Decomment to add new branch TickerNumber-XXX
  #INTEG_REF: /^(develop|release|TickerNumber-XXX)$/
  INTEG_REF: /^(develop|release)$/

  PIP_INDEX_URL: "https://${PANDORA_ARTIFACTORY_USERNAME}:${PANDORA_ARTIFACTORY_KEY}@${UL_ARTIFACTORY_HOST}/artifactory/api/pypi/pypi/simple"
  # Runs Pylint only on the following directories
  PYLINT_FILES: src/libsgm_python tests
  # HACK: Override MYPY_FILES without files definition in order to reuse the config from mypy.ini
  MYPY_FILES: '--exclude "(.cache|.venv)"'

  # Tests
  TEST_CPP: $[[ inputs.test-cpp ]]

# Default configuration for all jobs
default:
  tags:
    - Usine_Logicielle
  timeout: 30 minutes

# Override to restrict scope of PIP_OPT redefinition
# Cf issue https://gitlab.com/to-be-continuous/sphinx/-/issues/4
.sphinx-base:
  variables:
    # The image follow PEP 668
    PIP_OPTS: "--break-system-packages"

# Override to install doxygen
sphinx-build:
  before_script:
    - !reference [.sphinx-scripts]
    # Running make install to generate the documentation for c_libsgm
    - make ${TRACE+-d} install
    - source venv/bin/activate
    - install_ca_certs "${CUSTOM_CA_CERTS:-$DEFAULT_CA_CERTS}"
    # Install doxygen for C++ documentation
    - apt update -y && apt install -y doxygen
    - cd "${SPHINX_PROJECT_DIR}"
    - prepare_sphinx

# Black job
py-black:
  stage: test

# Pylint job
py-lint:
  stage: test
  variables:
    PYTHON_EXTRA_DEPS: sgm-python

# Mypy job
py-mypy:
  stage: test

# C++ unit Test
unit-cpp-test:
  extends: .python-test
  coverage: /^lines:\s+(\d+\.*\d*\%)\s/  # Linear regression for the items to be verified
  variables:
  script:
    - install_requirements
    # ${TRACE+-d} define the log level
    # Run C++ test
    - make ${TRACE+-d} test-cpp
    # Generate C++ coverage
    - make ${TRACE+-d} coverage-cpp
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura  # Format used by SonarQube
        path: reports/gcovr-report.xml
    paths:
      # Path to the report file
      - reports/gcovr-report.xml
  rules:
    # exclude if $TEST_CPP not set
    - if: '$TEST_CPP != "true"'
      when: manual
      allow_failure: true
    - !reference [.test-policy, rules]

# CppCheck
cppcheck:
  extends: .python-test
  script:
    # ${TRACE+-d} define the log level
    - make ${TRACE+-d} cppcheck
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    paths:
      - reports/cppcheck-report.xml
  rules:
    - !reference [.test-policy, rules]

# GitHub push
github-sync:
  stage: .post
  image:
    name: ${UL_ARTIFACTORY_HOST}/publicremotes-docker/alpine/git
    entrypoint: [""]
  variables:
    # Ensure we fetch enought history before pushing it
    GIT_DEPTH: 100
  before_script:
    # Ajout des certificats CNES
    - mkdir /usr/local/share/ca-certificates/
    - cat ${CNES_CERTIFICATE} > /usr/local/share/ca-certificates/my-cert.crt
    - cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt
  script:
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo "GITHUB_URL=$GITHUB_URL"
    - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
    - git remote add github https://${PANDORA_CNES_GITHUB_TOKEN_USERNAME}:${PANDORA_CNES_GITHUB_TOKEN_PASSWORD}@${GITHUB_URL}
    - git fetch origin ${CI_COMMIT_SHA}
    - git checkout -B ${CI_COMMIT_REF_NAME}
    - git push github ${CI_COMMIT_REF_NAME}
  rules:
    # run on production and integration branches + release pipelines
    - !reference [.delivery-policy, rules]
